server:
  port: 8762

spring:
  application:
    name: service-hi
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8
    username: mytest
    password: 111111
  jpa:
    show-sql: true
    database: MYSQL
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
mybatis:
  mapper-locations: classpath*:mapper/*Dao.xml
  type-aliases-package: spring.cloud.ykf.eureka.provide.user.vo
